image: maven:3.9.6-eclipse-temurin-17

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: build
  script:
    - mvn -B -ntp compile

test:
  stage: test
  script:
    - mvn -B -ntp verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
