server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist
    username: todolist
    password: todolist
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    com.mipt.angelikaliber: DEBUG
    org.springframework.web: DEBUG

app:
  name: To-Do List Manager (dev)
